server :
  port : 50011
  ips :
    - "127.0.0.1/32"
    - "172.18.0.0/16"
    - "172.17.0.0/16"
    - "172.16.0.0/12"
    - "192.168.0.0/16"

coins :

  btc :
    node : https://btc1.trezor.io
    fee : 10
    hashType : 0x01
    minUTXOConfirmation : 1
    sequenceUnitMax : 4294967294
    subAmount : 8

  eth :
    node : https://eth1.trezor.io
    subAmount : 18
    fee : 10

  trx :
    node : https://api.shasta.trongrid.io
    subAmount : 6
    fee : 1000000